Web_VideoEditing/Web_VideoEditing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/",include('users.urls')),
    path("", include('clients.urls')),
    path("administrators/", include('administrators.urls')),
    path("user_project/", include('user_project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_VideoEditing/administrators/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin

app_name = 'administrators'
urlpatterns = [
    path('', views.index, name="index"),
    path('detail_user', views.detail_user, name="detail_user"),
    # path('index', views.index, name="index"),
    path('table', views.table, name="table"),
    path('add_user', views.add_user, name="add_user"),
    path('video_user/<int:pk>/', views.video_user, name='video_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('video/delete/<int:user_id>/<int:video_id>/', views.delete_video, name='delete_video'),
]

Web_VideoEditing/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

Web_VideoEditing/administrators/models.py
from django.db import models

# Create your models here.

Web_VideoEditing/administrators/forms.py
from django import forms
from users.models import Users

class UserForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['username', 'email', 'role', 'image']

Web_VideoEditing/administrators/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from users.views import base_context
from users.models import Users
from clients.models import Video, UserUpload
from .forms import UserForm
from django.contrib.auth.hashers import make_password
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
import os
from django.conf import settings





def check_user_role(request):
    if 'username' not in request.session:
        return redirect('users:signin')
    
    username = request.session.get('username', None)
    user_profile = Users.objects.get(username=username) if username else None
    
    if user_profile.role == 'client':
        return redirect('user_project:index',id=user_profile.id)
    
    return None

def detail_user(request):
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    
    context = base_context(request)
    return render(request, 'administrators/detail_user.html', context)

def index(request):
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    
    context = base_context(request)
    return render(request, 'administrators/index.html', context)

def table(request):
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    users_data = Users.objects.all()
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request, 'administrators/table.html',{'users_data': users_data, 'user_profile': user_profile})


def delete_user(request, user_id):
    try:
        user = Users.objects.get(id=user_id)
        user.delete()
    except Users.DoesNotExist:
        pass
    return redirect('administrators:table') 

def add_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        role = request.POST['role']
        image = request.FILES.get('image', 'default.jpg')
        if Users.objects.filter(username=username).exists():
            error_message = '**Username already exists.'
            return JsonResponse({'error_message': error_message})
        
        # Kiểm tra email và tính hợp lệ của email
        try:
            Users.objects.get(email=email)
            email_message = '**Email already exists.'
            return JsonResponse({'email_message': email_message})
        except Users.DoesNotExist:
            try:
                validate_email(email)
            except ValidationError:
                email_message = '**Invalid email.'
                return JsonResponse({'email_message': email_message})
        
        #check password least 8 characters
        if len(password) < 8:
            password_message = '**Password must be at least 8 characters long.'
            return JsonResponse({'password_message': password_message})
        
        hashed_password = make_password(password)
        mysqluser = Users(username=username, email=email, password=hashed_password, role=role, image=image)
        # dd(mysqluser)
        mysqluser.save()
    
        return redirect('administrators:table') 
    
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request,'administrators/add_user.html',{'user_profile':user_profile})

def update_user(request, user_id):
    user = Users.objects.get(id=user_id)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('administrators:table')
    else:
        form = UserForm(instance=user)
    
    context = base_context(request)
    user_profile = context['user_profile']

    return render(request, 'administrators/update_user.html', {'form': form, 'user': user, 'user_profile':user_profile})

def video_user(request, pk):
    context = base_context(request)
    user_profile = context['user_profile']
    # Lấy dữ liệu video của người dùng với id tương ứng
    videos = Video.objects.filter(user_id=pk)
    print(videos)
    return render(request, 'administrators/video_user.html', {'videos': videos, 'user_id': pk, 'user_profile':user_profile})


# def delete_video(request, user_id, video_id):
#     # Retrieve the video based on the provided video_id
#     video = Video.objects.get(id=video_id)
    
#     # Perform any necessary checks or validations before deleting the video
    
#     # Delete the video
#     video.delete()
    
#     # Redirect the user to the desired page after successful deletion
#     return redirect('administrators:video_user', pk=user_id)

def delete_video(request, user_id, video_id):
    # Retrieve the video based on the provided video_id
    video = Video.objects.get(id=video_id)
    
    # Delete the associated video_edit file
    video_edit_path = os.path.join(settings.MEDIA_ROOT, str(video.video_edit))
    if os.path.exists(video_edit_path):
        os.remove(video_edit_path)
    
    # Delete the associated upload file
    upload_path = os.path.join(settings.MEDIA_ROOT, str(video.upload_id.path_video))
    if os.path.exists(upload_path):
        os.remove(upload_path)
    
    # Delete the video record
    video.delete()
    
    # Redirect the user to the desired page after successful deletion
    return redirect('administrators:video_user', pk=user_id)

Web_VideoEditing/administrators/templates/administrators/add_user.html
{% extends 'base.html' %} {% load static %} {% block title %} Add_user {% endblock %} {% block css %}
<!-- Custom styles for this page -->
<link href="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet"> {% endblock %} {% block container_fluid %}
<link href="{% static 'administrators/css/add_user.css' %}" rel="stylesheet">
<div class="container-fluid">
    <div class="add_user">

        <h1>Add User</h1>
        <form action="{% url 'administrators:add_user' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Username</label>
                <input type="username" class="form-control" name="username" id="username"  placeholder="Enter username">
              </div>
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect1">Role select</label>
                <select class="form-control" id="role" name="role">
                  <option>admin</option>
                  <option>client</option>
                </select>
              </div>
              <div class="form-group">
                <label for="exampleFormControlFile1">Image file</label>
                <input type="file"  name="image" class="form-control-file" id="image" accept="image/jpeg, image/png">
              </div>
            <button type="submit" class="btn btn-primary">Save</button>
          </form>
    </div>
</div>
{% endblock %} {% block js_body %}
<!-- Data Tables -->
<script src="{% static 'administrators/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'administrators/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

Web_VideoEditing/administrators/templates/administrators/base_admin.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
  <link rel="stylesheet" href="{% static 'administrators/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'administrators/css/index_admin.css' %}">
  <link rel="stylesheet" href="{% static 'administrators/css/detail_user.css' %}">


  {% if title %}
  <title>Video Clips Editor</title>
  {% else %}
  <title>Video Clips Editor</title>
  {% endif %}

</head>
<body id="body-pd">
<header class="header" id="header">
  <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
  <div class="form">
    <i class="fa-solid fa-magnifying-glass"></i>
    <input type="text" class="form-control form-input" placeholder="Search anything...">
  </div>
  <div class="header_img">
    <img src="{% static 'administrators/images/default.jpg' %}" alt="">
    {% comment %} {% if user_profile %}
    <p>Welcome, {{ user_profile.username }}!</p>
    {% if user_profile.image %}
            <img src="{{ user_profile.image.url }}" alt="{{ user_profile.username }}'s profile picture" class="round_image">
        {% endif %}
    {% else %}
    <p>Welcome, Guest!</p>
    {% endif %} {% endcomment %}
  </div>
</header>
<div class="l-navbar" id="nav-bar">
  <nav class="nav">
    <div><a href="#" class="nav_logo"> <i class='bx bx-layer nav_logo-icon'></i> <span
        class="nav_logo-name">Video Editor</span> </a>
      <div class="nav_list">
        <a href="#" class="nav_link active">
            <i class="fa-regular fa-user"></i>
          {% comment %} <i class='bx bx-captions nav_icon'></i> {% endcomment %}
          <span class="nav_name">User</span>
        </a>
        {% comment %} <a href="#" class="nav_link">
          <i class='bx bx-podcast nav_icon'></i>
          <span class="nav_name">Merge Audio to Video</span>
        </a>
        <a href="#" class="nav_link">
          <i class='bx bx-text nav_icon'></i>
          <span class="nav_name">Add Text To Video</span>
        </a> {% endcomment %}
        <a href="/settings" class="nav_link">
          <i class='bx bx-cog nav_icon'></i>
          <span class="nav_name">Settings</span>
        </a>
      </div>
    </div>
    <a href="#" class="nav_link"> <i class='bx bx-log-out nav_icon'></i> <span class="nav_name">SignOut</span> </a>
  </nav>
</div>
<!--Container Main start-->
<div class="container-fluid">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}

    {% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<script src="{% static 'administrators/js/sidebar.js' %}"></script>
</body>
</html>

Web_VideoEditing/administrators/templates/administrators/detail_user.html
 {% extends "administrators/base_admin.html" %} {% block content %}
<div class="container">
    <div>
        <h3>User - NgocAnh</h3>
    </div>
    <div class="main1">
        <div class="container">
            <div class="row">
                <div class="col-sm" style="position: relative;height: 225px;width: 225px">
                    {% load static %}
                    <img src="{% static 'administrators/images/1.PNG' %} " alt=" " class="image1 " style="height: 225px;width: 225px;display: block; ">
                    <i class="fa-solid fa-ellipsis-vertical" style=" position: absolute;top: 12%; left: 60%;transform: translate;z-index: 1;font-weight: bold;font-size: 20px;color:#fff"></i>
                    <p style=" position: absolute;top: 10%; left: 7%;transform: translate;z-index: 1;font-weight: bold;font-size: 20px;color:#fff ">Sun_video</p>
                    <p style=" position: absolute;top: 88%; left: 5%;transform: translate;z-index: 1;font-weight: bold;font-size: 14px;color:#fff ">00:13</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Web_VideoEditing/administrators/templates/administrators/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Index {% endblock %}

{% block container_fluid %}
{% endblock %}

{% block js_body %}
	{% comment %} {% include 'theme/components/charts_scripts.html' %} {% endcomment %}
{% endblock %}

Web_VideoEditing/administrators/templates/administrators/index_admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% extends "administrators/base_admin.html" %} {% block content %}
    <div class="container">
        <div>
            <h3>All User</h3>
        </div>
        <div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Role</th>
                        <th scope="col">Image</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>NgocAnh</td>
                        <td>ngocanh@gmail.com</td>
                        <td>client</td>
                        <td>
                            <a href="">default.jpg</a>
                        </td>
                        <td class="action"><i class="fa-solid fa-pen-to-square"></i> | <i class="fa-solid fa-trash"></i></td>
                    </tr>
                    <tr>
                        <th scope="row">2</th>
                        <td>Nganguyen</td>
                        <td>nga@gmail.com</td>
                        <td>client</td>
                        <td>
                            <a href="">default.jpg</a>
                        </td>
                        <td class="action"><i class="fa-solid fa-pen-to-square"></i> | <i class="fa-solid fa-trash"></i></td>
                    </tr>
                    <tr>
                        <th scope="row">3</th>
                        <td>thuynguyen</td>
                        <td>thuy@gmail.com</td>
                        <td>client</td>
                        <td>
                            <a href="">default.jpg</a>
                        </td>
                        <td class="action"><i class="fa-solid fa-pen-to-square"></i> | <i class="fa-solid fa-trash"></i></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {% endblock content %}
</body>

</html>

Web_VideoEditing/administrators/templates/administrators/table.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Tables {% endblock %}


{% block css %}
<!-- Custom styles for this page -->
<link href="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock %}

{% block container_fluid %}
<div class="container-fluid">
    <!-- Page Heading -->
  {% comment %} <h1 class="h3 mb-2 text-gray-800">Tables</h1> {% endcomment %}
  <button class="orange-button">Add User</button>
    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">User Management</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>UseName</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Create date</th>
                            <th>Image</th>
                            <th>Action</th>

                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>UseName</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th>Create date</th>
                            <th>Image</th>
                            <th>Action</th>

                        </tr>
                    </tfoot>
                    <tbody>  

                        {% for user in users_data %}
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.role }}</td>
                            <td>{{ user.create_at }}</td>
                            <td><img src="{{ user.image.url }}" alt="{{ user.username }}'s image" style="max-width: 50px; max-height: 50px;"></td>
                            <td>
                                <a href="#" class="btn btn-danger btn-circle btn-sm"><i class="fa-regular fa-pen-to-square"></i></a>
                                <a href="#" class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
<!-- Data Tables -->
<script src="{% static 'administrators/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'administrators/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

Web_VideoEditing/administrators/templates/administrators/update_user.html
{% extends 'base.html' %} {% load static %} {% block title %} Add_user {% endblock %} {% block css %}
<!-- Custom styles for this page -->
<link href="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet"> {% endblock %} {% block container_fluid %}
<link href="{% static 'administrators/css/update_user.css' %}" rel="stylesheet">
<div class="container-fluid">
    <div class="add_user">
        <h1>Update User</h1>
        <form action="{% url 'administrators:update_user' user_id=user.id %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="Enter username" value="{{ user.username }}">
            </div>
            <div class="form-group">
                <label for="email">Email address</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label for="role">Role select</label>
                <select class="form-control" id="role" name="role">
                    <option value="admin" {% if user.role == 'admin' %}selected{% endif %}>Admin</option>
                    <option value="client" {% if user.role == 'client' %}selected{% endif %}>Client</option>
                </select>
            </div>
            <div class="form-group">
                <label for="image">Image file</label>
                <input type="file" class="form-control-file" id="image" name="image" accept="image/jpeg, image/png">
            </div>
            <button type="submit" class="btn btn-primary">Update User</button>
        </form>
    </div>
</div>
{% endblock %}
{% block js_body %}
<!-- Data Tables -->
<script src="{% static 'administrators/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'administrators/js/demo/datatables-demo.js' %}"></script>
{% endblock %}

Web_VideoEditing/administrators/templates/administrators/video_user.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Tables {% endblock %}

{% block css %}
<!-- Custom styles for this page -->
<link href="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
<link href="{% static 'administrators/css/video_user.css' %}" rel="stylesheet">
{% endblock %}

{% block container_fluid %}
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Video Edit</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Title</th>
                            <th>Video edit</th>
                            <th>Duration</th>
                            <th>Format</th>
                            <th>Size</th>
                            <th>Video upload</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>STT</th>
                            <th>Title</th>
                            <th>Video edit</th>
                            <th>Duration</th>
                            <th>Format</th>
                            <th>Size</th>
                            <th>Video upload</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        {% for video in videos %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ video.title }}</td>
                            <td>{{ video.video_edit }}</td>
                            <td>{{ video.duration }}</td>
                            <td>{{ video.format }}</td>
                            <td>{{ video.size }}</td>
                            <td>{{ video.video_upload }}</td>
                            <td>
                                {% comment %} <a href="{% url 'administrators:update_user' user_id=user.id %}" class="btn btn-danger btn-circle btn-sm update"><i class="fa-regular fa-pen-to-square"></i></a> {% endcomment %}
                                <a href="{% url 'administrators:delete_video' user_id=user_id video_id=video.id %}" class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash"></i></a></td>
                                {% comment %} <a href="{% url 'administrators:delete_user' user.id%}" class="btn btn-danger btn-circle btn-sm"><i class="fas fa-trash"></i></a> {% endcomment %}
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block js_body %}
<!-- Data Tables -->
<script src="{% static 'administrators/vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'administrators/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'administrators/js/demo/datatables-demo.js' %}"></script>
{% endblock %}