Web_VideoEditing/Web_VideoEditing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/",include('users.urls')),
    path("", include('clients.urls')),
    path("administrators/", include('administrators.urls')),
    path("user_project/", include('user_project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_VideoEditing/user_project/urls.py
from django.urls import path
from . import views

app_name = 'user_project'
urlpatterns = [
path('<int:id>/', views.home, name='index'),
path('forgot_password/', views.forgot_password, name='forgot_password'),
path('profile/<int:user_id>/', views.profile, name='profile'),
path('delete_video/<int:pk>/', views.delete_video, name='delete_video'),
path('edit_user/', views.edit_user, name='edit_user'),
# path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
path('download_video/<int:pk>/', views.download_video, name='download_video'),
path('edited_video/', views.edited_video, name='edited_video'),



]

Web_VideoEditing/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

Web_VideoEditing/user_project/views.py
from django.shortcuts import render, redirect
from users.models import Users
from clients.models import Upload, UserUpload
from django.http import HttpResponse
from django.urls import reverse
from users.views import base_context
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
import os
from django.http import FileResponse
from django.utils.encoding import smart_str


def check_user_role(request):
    if 'username' not in request.session:
        return redirect('users:signin')
    username = request.session.get('username', None)
    user_profile = Users.objects.get(username=username) if username else None
    if user_profile.role == 'admin':
        return redirect('administrators:index')
    return None

def home(request, id):
    user = Users.objects.get(pk=id)
    user_uploads = UserUpload.objects.filter(user=user)
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request, 'user_project/index.html', {'user': user, 'user_uploads': user_uploads, 'user_profile': user_profile})

def forgot_password(request):
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request, 'user_project/forgot_password.html',{'user_profile': user_profile})

# def profile(request,user_id):
#     user_profile1 = Users.objects.get(id=user_id)
#     context = base_context(request)
#     user_profile = context['user_profile']
#     return render(request, 'user_project/profile.html', {'user_profile1':user_profile1,'user_profile':user_profile})

def profile(request, user_id):
    user_profile1 = get_object_or_404(Users, id=user_id)
    context = base_context(request)
    user_profile = context['user_profile']

    if request.method == 'POST':
        # Retrieve the submitted form data
        new_name = request.POST.get('editName')
        new_email = request.POST.get('editEmail')
        new_image = request.FILES.get('image')

        # Update the user profile
        user_profile1.username = new_name
        user_profile1.email = new_email

        # Save the uploaded image if provided
        if new_image:
            user_profile1.image = new_image

        user_profile1.save()

    return render(request, 'user_project/profile.html', {'user_profile1': user_profile1, 'user_profile': user_profile})


def delete_video(request, pk):
    user_upload = get_object_or_404(UserUpload, pk=pk)
    user_upload.delete()
    return redirect('user_project:index', id=user_upload.user.id)

def edit_user(request):
    pass

# def download_video(request, pk):
#     user_upload = get_object_or_404(UserUpload, pk=pk)
#     user_upload.delete()
#     return redirect('user_project:index', id=user_upload.user.id)

def download_video(request, pk):
    upload = get_object_or_404(Upload, pk=pk)

    # Get the path of the video file
    video_path = upload.path_video.path

    # Open the video file
    video_file = open(video_path, 'rb')

    # Create a FileResponse with the video file
    response = FileResponse(video_file)

    # Set the content type and headers for the response
    response['Content-Type'] = 'video/mp4'
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(upload.path_video.name)

    return response



def edited_video(request):
    return render(request, 'user_project/edited_video.html')

Web_VideoEditing/user_project/templates/user_project/components/navbar.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Search -->
    <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                            <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
        <div class="topbar-divider d-none d-sm-block"></div>
        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            {%if user_profile%}
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user_profile.username }}</span>
            <img class="img-profile rounded-circle" src="{{ user_profile.image.url }}">
            </a>
            {% endif%}
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#"> <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i> Profile </a>
                <a class="dropdown-item" href="#"> <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i> Settings </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'users:signout'%}" data-toggle="modal" data-target="#logoutModal"> <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i> Logout </a>
            </div>
        </li>
    </ul>
</nav>

Web_VideoEditing/user_project/templates/user_project/components/navbar_x.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <div class="d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100">
    </div>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link login-top-right-link">
            <a class="nav-link dropdown-toggle"  id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Login</span>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-sign-in-alt fa-fw"></i>
                </span>
            </a>
        </li>

        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link register-top-right-link">
            <a class="nav-link dropdown-toggle" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Register</span>

                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-user-plus fa-fw"></i>
                </span>
            </a>
        </li>
    </ul>
</nav>

Web_VideoEditing/user_project/templates/user_project/components/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
      <a class="nav-link">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-fw fa-folder"></i>
        <span>Pages</span>
      </a>
      <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Login Screens:</h6>
          <a class="collapse-item" href="{% url 'user_project:forgot_password' %}">Forgot Password</a>
          <div class="collapse-divider"></div>
          <h6 class="collapse-header">Other Pages:</h6>
          {% if user.id %}
          <a class="collapse-item" href="{% url 'user_project:profile' user.id %}">Profile</a>
        {% endif %}
        </div>
      </div>
    </li>
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>