Web_VideoEditing/Web_VideoEditing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/",include('users.urls')),
    path("", include('clients.urls')),
    path("administrators/", include('administrators.urls')),
    path("user_project/", include('user_project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_VideoEditing/clients/urls.py
from django.urls import path, include
from .import views

app_name = 'clients'
urlpatterns = [
    path('', views.home, name="home"),
    path('all_tools/', views.all_tools, name="all_tools"),
    path('add_subtitles/', views.subtitle_video, name="add_subtitles"),
    path('add_subtitles_tool/<int:id>/<int:subtitle_id>/', views.add_subtitles_tool, name="add_subtitles_tool"),
    path('preview_add_subtitles', views.preview_add_subtitles, name="preview_add_subtitles"),
    path('subtitle/<int:id>/', views.subtitle, name="subtitle"),
    path('merge_video/', views.merge_video, name="merge_video"),
    path('preview_merge_video/', views.preview_merge_video, name='preview_merge_video'),
    path('merge_tools/<int:id>/', views.merge_tools, name="merge_tools"),
    path('export_merge_video', views.export_merge_video, name="export_merge_video"),
    path('crop_video/', views.crop_video, name="crop_video"),
    path('crop_tool/<int:id>/', views.crop_tool, name="crop_tool"),
    path('preview_crop_video', views.preview_crop_video, name="preview_crop_video"),
    path('export_crop_video', views.export_crop_video, name="export_crop_video"),
    path('cut_tool/<int:id>/', views.cut_tool, name="cut_tool"),
    path('cut_video/', views.cut_video, name="cut_video"),
    path('loop_video/', views.loop_video, name="loop_video"),
    path('loop_tool/<int:id>/', views.loop_tool, name="loop_tool"),
    path('export_loop_video', views.export_loop_video, name="export_loop_video"),
    path('preview_cut_video', views.preview_cut_video, name="preview_cut_video"),
    path('export_video', views.export_video, name="export_video"),
    path('add_voice_tool/<int:id>/<int:subtitle_id>/', views.add_voice_tool, name="add_voice_tool"),
    path('add_voice/', views.add_voice, name="add_voice"),
    path('subtitle_voice/<int:id>/', views.subtitle_voice, name="subtitle_voice"),
    path('upload_subtitle', views.upload_subtitle, name="upload_subtitle"),
    path('preview_voice_to_video', views.preview_voice_to_video, name="preview_voice_to_video"),


]

Web_VideoEditing/user_project/urls.py
from django.urls import path
from . import views

app_name = 'user_project'
urlpatterns = [
path('<int:id>/', views.home, name='index'),
path('forgot_password/', views.forgot_password, name='forgot_password'),
path('profile/<int:user_id>/', views.profile, name='profile'),
path('delete_video/<int:pk>/', views.delete_video, name='delete_video'),
path('edit_user/', views.edit_user, name='edit_user'),
# path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
path('download_video/<int:pk>/', views.download_video, name='download_video'),
path('edited_video/', views.edited_video, name='edited_video'),



]

Web_VideoEditing/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

Web_VideoEditing/clients/models.py
from django.db import models
from users.models import Users

# Create your models here.
class Subtitle(models.Model):
    path = models.FileField(upload_to='audio_files/')
    name = models.CharField(max_length=100)
    
    class Meta:
        db_table = "Subtitle"

class Upload(models.Model):
    path_video = models.FileField(max_length=200, upload_to='Files/')
    title_video = models.CharField(max_length=200, null=True)
    path_image = models.FileField(upload_to='Files/', null=True)
    
    class Meta:
        db_table = "Upload"


class UserUpload(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "UserUpload"
    
class Video(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    video_edit = models.FileField(upload_to='video_edits/')
    duration = models.IntegerField()
    format = models.CharField(max_length=50)
    size = models.IntegerField()
    update_date = models.DateTimeField()
    thumb = models.ImageField(upload_to='video_thumbs/')
    user_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    subtitle_id = models.ForeignKey(Subtitle, null=True, on_delete=models.CASCADE)
    upload_id = models.ForeignKey(Upload, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "Video"

Web_VideoEditing/clients/forms.py
from django import forms
from .models import Upload

class FileUploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = ['path_video']

Web_VideoEditing/clients/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from users.models import Users
from django.http import HttpResponse, JsonResponse
import os
import json
from django.conf import settings
from .forms import FileUploadForm
from users.views import base_context
from moviepy.video.io.ffmpeg_tools import ffmpeg_extract_subclip
from .models import Upload,UserUpload
from .models import Upload,UserUpload, Video, Subtitle
import uuid
from moviepy.editor import VideoFileClip, vfx, AudioFileClip, concatenate_audioclips, concatenate_videoclips, TextClip, CompositeVideoClip, VideoClip
from datetime import datetime
from pydub import AudioSegment
import re
import time
import requests
import subprocess
import json

def home(request):
    context = base_context(request)
    return render(request, 'clients/index.html', context)

def all_tools(request):
    context = base_context(request)
    return render(request, 'clients/all_tools.html', context)

def subtitle_video(request):
    context = base_context(request)
    if request.method == 'POST' and 'video_file' in request.FILES:
        if request.session.get('user_id') is None:
            return redirect('users:signin')
        video_file = request.FILES['video_file']
        title = video_file.name
        upload = Upload(path_video=video_file, title_video=title, path_image='')
        upload.save()
        upload_id = upload.id
        user_upload = UserUpload(upload_id=upload_id, user_id=request.session.get('user_id'))
        user_upload.save()
        redirect_url = reverse('clients:subtitle', kwargs={'id': upload_id})
        return redirect(redirect_url)
    else:
        return render(request, 'clients/add_subtitles.html', context)

def add_subtitles_tool(request, id, subtitle_id):
    upload = Upload.objects.get(id=id)
    subtitle = Subtitle.objects.get(id=subtitle_id)
    if subtitle.path.path is not None:
        subtitles = detect_subtitle(subtitle.path.path)
    data = {
        'id':id,
        'video_url': upload.path_video.url,
        'full_path': upload.path_video.path,
        'subtitles': subtitles
    }

    return render(request, "clients/add_subtitle_tool.html", data)

def detect_subtitle(path):
    with open(path, 'r', encoding='utf-8') as srt_file:
        srt_lines = srt_file.readlines()
    subtitles = []
    for i in range(0, len(srt_lines), 4):
        time_line = srt_lines[i + 1].strip()
        if is_valid_time_format(time_line):
            start_time, end_time = time_line.split(' --> ')
            text = srt_lines[i + 2].strip()
            subtitle = {
                'start_time': format_time(start_time),
                'end_time': format_time(end_time),
                'text': text
            }
            subtitles.append(subtitle)
    return subtitles
    # Kết hợp (merge) các audio trong danh sách
def preview_add_subtitles(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        upload = Upload.objects.get(id=id)
        input_video_path = request.POST.get('video_path')
        video = VideoFileClip(upload.path_video.path)
        final_video = os.path.join(settings.BASE_DIR, 'media/Files/previews/output.mp4')
        subtitles = request.POST.get('subtitles')
        subtitles = json.loads(subtitles)
        video_clips = sub_clips = []
        for sub in subtitles:
            start_time = format_time_to_seconds(sub["start_time"])
            end_time = format_time_to_seconds(sub["end_time"])
            videoClip = video.subclip(start_time, end_time)
            text = sub["text"]
            font_size = int(min(video.size) / 20)
            # Insert line breaks based on video width and maximum characters per line
            max_chars_per_line = int(video.size[0] / font_size)
            text_with_line_breaks = insert_line_breaks(text, max_chars_per_line)
            subtitle_clip = generate_subtitle(text_with_line_breaks, start_time , end_time, font_size)
            sub_clips.append(subtitle_clip)
        video_with_subtitles = CompositeVideoClip([video] + sub_clips)
        video_with_subtitles.write_videofile(final_video, codec="libx264", audio_codec="aac",fps=24)


        return JsonResponse({'preview_video' : '/media/Files/previews/output.mp4'})
# Function to insert line breaks in text based on width
def insert_line_breaks(text, max_chars):
    words = text.split()
    lines = []
    current_line = ""

    for word in words:
        if len(current_line + " " + word) <= max_chars:
            current_line += " " + word
        else:
            lines.append(current_line.strip())
            current_line = word

    lines.append(current_line.strip())
    return "\n".join(lines)

def format_time_to_seconds(time):
# Split the time string into minutes, seconds, and milliseconds
    minutes, seconds = map(float, time.split(':'))

    # Convert the time to seconds
    total_seconds = (minutes * 60) + seconds
    return total_seconds

def generate_subtitle(subtitle_text, start_time, end_time, font_size):
    duration = end_time - start_time
    textClip = TextClip(subtitle_text, fontsize=font_size, font='Arial', color='white', bg_color='black')
    # Calculate the desired padding (in pixels)
    padding_x = 20  # Horizontal padding
    padding_y = 20  # Vertical padding

    # Increase the size of the text clip to add padding
    textClip = textClip.margin(left=padding_x, right=padding_x, top=padding_y, bottom=padding_y)
    textClip = textClip.set_start(start_time).set_end(end_time).set_duration(duration).set_position(("center", "bottom"))
    return textClip

def format_time(time):
    # Parse the input time string
    time_obj = datetime.strptime(time, '%H:%M:%S,%f')
    # Calculate total seconds with microseconds truncated to two decimal places
    total_seconds = time_obj.second + (time_obj.microsecond / 10**6)
    formatted_time = f"{time_obj.minute:02}:0{total_seconds:.2f}"
    return formatted_time

def subtitle(request, id):
    context = base_context(request)
    if request.method == 'POST' and 'sub_file' in request.FILES:
        if request.session.get('user_id') is None:
            return redirect('users:signin')
        sub_file = request.FILES['sub_file']
        path_file = os.path.join(settings.BASE_DIR, f"media/Files/{sub_file.name}")
        name = sub_file.name
        subtitle = Subtitle(path=sub_file, name=name)
        subtitle.save()
        subtitle_id = subtitle.id
        redirect_url = reverse('clients:add_subtitles_tool', kwargs={'id': id,'subtitle_id':subtitle_id})
        return redirect(redirect_url)

    return render(request, "clients/subtitle.html", {'id':id})

def subtitle_voice(request, id):
    context = base_context(request)
    if request.method == 'POST' and 'sub_file' in request.FILES:
        if request.session.get('user_id') is None:
            return redirect('users:signin')
        sub_file = request.FILES['sub_file']
        path_file = os.path.join(settings.BASE_DIR, f"media/Files/{sub_file.name}")
        name = sub_file.name
        subtitle = Subtitle(path=sub_file, name=name)
        subtitle.save()
        subtitle_id = subtitle.id
        redirect_url = reverse('clients:add_voice_tool', kwargs={'id': id,'subtitle_id':subtitle_id})
        return redirect(redirect_url)

    return render(request, "clients/subtitle_voice.html", {'id':id})

def add_voice(request):
    context = base_context(request)
    if request.method == 'POST' and 'video_file' in request.FILES:
        if request.session.get('user_id') is None:
            return redirect('users:signin')
        video_file = request.FILES['video_file']
        title = video_file.name
        upload = Upload(path_video=video_file, title_video=title, path_image='')
        upload.save()
        upload_id = upload.id
        user_upload = UserUpload(upload_id=upload_id, user_id=request.session.get('user_id'))
        user_upload.save()
        redirect_url = reverse('clients:subtitle_voice', kwargs={'id': upload_id})
        return redirect(redirect_url)
    else:
        return render(request, 'clients/add_voice.html', context)

def upload_subtitle(request):
    context = base_context(request)
    if request.method == 'POST' and 'sub_file' in request.FILES:
        sub_file = request.FILES['sub_file']
        path_file = os.path.join(settings.BASE_DIR, f"media/Files/{sub_file.name}")
        # Save the uploaded file to the specified location
        with open(path_file, 'wb') as file_destination:
            for chunk in sub_file.chunks():
                file_destination.write(chunk)
        return JsonResponse({'path_sub' : path_file})
    else:
        return render(request, 'clients/add_voice.html', context)

def preview_voice_to_video(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        upload = Upload.objects.get(id=id)
        input_video_path = request.POST.get('video_path')
        final_video = os.path.join(settings.BASE_DIR, 'media/Files/previews/output.mp4')
        subtitles = request.POST.get('subtitles')
        subtitles = json.loads(subtitles)
        final_video = handle_sub(input_video_path, subtitles)
        return JsonResponse({'preview_video' : final_video})

def handle_sub(path_video, subtitles):
    video_clip = VideoFileClip(path_video)
    output_audio_file = os.path.join(settings.BASE_DIR, 'media/Files/output_audio.mp3')
    final_video = os.path.join(settings.BASE_DIR,'media\Files\previews\output.mp4')
    video_file = path_video
    audio_clips = []
    for sub in subtitles:
        start_time = format_time_to_seconds(sub["start_time"])
        end_time = format_time_to_seconds(sub["end_time"])
        videoClip = video_clip.subclip(start_time, end_time)
        text = sub["text"]
        url = 'https://api.fpt.ai/hmi/tts/v5'
        payload = text
        headers = {
            'api-key': 'abAl9piv7XGwHVn5onzLLzTrNGbh5LPZ',
            'speed': '',
            'voice': 'banmai'
        }

Web_VideoEditing/clients/templates/clients/base_tool.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />
    <link rel="stylesheet" href="{% static 'clients/bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
<!--    <link rel="stylesheet" href="{% static 'clients/css/all.min.css' %}"/>-->
    <link rel="stylesheet" href="{% static 'clients/css/global.css' %}"/>
    <link rel="stylesheet" href="{% static 'clients/css/base.css' %}"/>
    {% block stylesheets %}

    {% endblock stylesheets %}
</head>

<body>
<div class="main-tool">
    {% block content %}
    {% endblock  %}
</div>
<script src="{% static 'clients/js/jquery-3.6.4.min.js' %}"></script>
<script src="{% static 'clients/js/jquery-ui.min.js' %}"></script>
<script src="{% static 'clients/js/loadingoverlay.min.js' %}"></script>
<script src="{% static 'clients/bootstrap/js/bootstrap.js' %}"></script>
{% block script %}

{% endblock script %}
</body>
</html>

Web_VideoEditing/clients/templates/clients/index.html
{% extends "clients/base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" href="{% static 'clients/css/index.css' %}" />
{% endblock stylesheets %}
{% block content %}
<div class="view" style="background-image: url('/static/clients/images/pexelsjessicalewis593324-2%402x.png'); height: 700px; background-repeat: no-repeat; background-size: cover; background-position: center center;">
    <!-- Mask & flexbox options-->
    <div class="mask rgba-gradient align-items-center">
        <!-- Content -->
        <div class="container">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-md-6 white-text text-center text-md-left mt-xl-5 mb-5 wow fadeInLeft" data-wow-delay="0.3s">
                    <h1 class="h1-responsive font-weight-bold mt-sm-5">Make Your Interior More Minimaistic & Modern</h1>
                    <hr class="hr-light">
                    <h6 class="mb-4">All-in-one easy-to-use online video tools</h6>
                </div>
            </div>
            <!--Grid row-->
        </div>
        <!-- Content -->
    </div>
    <!-- Mask & flexbox options-->
</div>
<div class="container">
    <div class="choosing-us pt-5 mt-5 text-center">
        <h1 class="mb-5">Why Choosing Us</h1>
        <div class="row justify-content-center">
            <div class="m-3">
                <div class="card d-flex align-items-center" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Completely Online</h5>
                        <p class="card-text">There is no need to download and install any app to your phone, tablet or computer — use the online Clideo tools instead.</p>
                    </div>
                </div>
            </div>
            <div class="m-3">
                <div class="card d-flex align-items-center" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Free</h5>
                        <p class="card-text">Kapwing is completely free to start. Just upload a video and start editing. Supercharge your editing workflow with our powerful online tools.</p>
                    </div>
                </div>
            </div>
            <div class="m-3">
                <div class="card d-flex align-items-center" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Powerful</h5>
                        <p class="card-text">Kapwing works hard to help make the content you want, when you want it. Get started on your project today.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="content-online-tools">
    <div class="container">
        <div class="online-tools pt-5 mt-5 text-center">
            <h1 class="mb-5">Online Video Tools</h1>
            <div class="row justify-content-center">
                <div class="m-3">
                    <a href="{% url 'clients:add_voice'%}" class="item">
                        <div class="card d-flex align-items-center" style="width: 18rem;">
                            <div class="card-body">
                                <img src="{% static 'clients/images/microphone.png' %}" width="50" height="50" alt="...">
                                <h5 class="card-title">Add voice to video</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="m-3">
                    <a href="{% url 'clients:loop_video'%}" class="item">
                        <div class="card d-flex align-items-center" style="width: 18rem;">
                            <div class="card-body">
                                <img alt="" src="{% static 'clients/images/video.png' %}" width="50" height="50" />
                                <h5 class="card-title">Loop Video</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="m-3">
                    <a href="{% url 'clients:cut_video'%}" class="item">
                        <div class="card d-flex align-items-center" style="width: 18rem;">
                            <div class="card-body">
                                <img src="{% static 'clients/images/video-editor.png' %}" width="50" height="50" alt="...">
                                <h5 class="card-title">Cut Video</h5>
                            </div>
                        </div>
                    </a>
                </div>
                <div class="m-3">
                    <a href="{% url 'clients:merge_video'%}" class="item">
                        <div class="card d-flex align-items-center" style="width: 18rem;">
                            <div class="card-body">
                                <img src="{% static 'clients/images/merge.png' %}" width="50" height="50" alt="...">
                                <h5 class="card-title">Merge Video</h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            <div class="m-3">
                <div class="all-tools"><a href="{% url 'clients:all_tools'%}">All tools<i class="fas fa-chevron-right"></i></a></div>
            </div>
        </div>
    </div>
</div>

<div class="content-aboutus pt-5 mt-5 pb-5">
    <div class="row justify-content-md-center">
        <div class="contract-left col col-lg-4">
            <p>
                Your all-in-one online video editor
                Make your own video from scratch, edit it and add music — all in one screen! Our seamless video editor allows you to manage the added media easily with the help of a multi-track timeline.
            </p>
        </div>
        <div class="contract-right col col-lg-2">
            <img class="image-47-icon" alt="" width="300" height="300" src="{% static 'clients/images/unsplashtqpypka92k8@2x.png' %}"/>
        </div>
    </div>
</div>

<!-- Full Page Intro-->
<!--<div class="index1">-->
<!--    <div class="nav">-->
<!--        <img class="pexels-jessica-lewis-593324-2-icon" alt="" src="{% static 'clients/images/pexelsjessicalewis593324-2@2x.png' %}" />-->
<!--        <div class="edit-video"><a href="{% url 'clients:home' %}">Edit video</a></div>-->
<!--        <div class="resources">Resources</div>-->
<!--        {% if user_profile %}-->
<!--        <div class="dropdown1">-->
<!--            <img src="{{ user_profile.image.url }}" class="dropbtn"/>-->
<!--            <div class="dropdown-content">-->
<!--                <a href="{% url 'user_project:index' id=user_profile.id %}">{{ user_profile.username }}</a>-->
<!--                <a href="{% url 'users:signout'%}">Log out</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% else %}-->
<!--        <div class="sign-in-wrapper">-->
<!--            <div class="sign-in">-->
<!--                <a href="{% url 'users:signin'%}">Sign in</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% endif %}-->
<!--    </div>-->

<!--    <div class="slide">-->
<!--        <div class="make-your-interior"> Make Your Interior More Minimaistic & Modern </div>-->
<!--        <div class="all-in-one-easy-to-use-online"> All-in-one easy-to-use online video tools </div>-->
<!--    </div>-->

<!--    <div class="reason">-->
<!--        <div class="rectangle-parent">-->
<!--            <div class="group-child"></div>-->
<!--            <div class="there-is-no"> There is no need to download and install any app to your phone, tablet or computer — use the online Clideo tools instead. </div>-->
<!--            <div class="completely-online"><p class="why">Completely Online</p> </div>-->
<!--        </div>-->
<!--        <div class="rectangle-group">-->
<!--            <div class="group-item"></div>-->
<!--            <div class="kapwing-is-completely"> Kapwing is completely free to start. Just upload a video and start editing. Supercharge your editing workflow with our powerful online tools. </div>-->
<!--            <div class="free"> <p class="why">Free</p> </div>-->
<!--        </div>-->
<!--        <div class="rectangle-container">-->
<!--            <div class="group-item"></div>-->
<!--            <div class="kapwing-works-hard">Kapwing works hard to help make the content you want, when you want it. Get started on your project today. </div>-->
<!--            <div class="powerful"><p class="why">Powerful</p> </div>-->
<!--        </div>-->
<!--        <div class="why-choosing-us-container">-->
<!--            <p class="why">Why</p>-->
<!--            <p class="why">Choosing Us</p>-->
<!--        </div>-->
<!--    </div>-->

<!--    <div class="tool">-->
<!--        <div class="online-video-tools">Online Video Tools</di  v>-->
<!--        <div class="next">-->
<!--            <div class="all-tools"><a href="{% url 'clients:all_tools'%}">All tools</a></div>-->
<!--            <img class="next-child" alt="" src="{% static 'clients/images/arrow-2@2x.png' %}" />-->
<!--        </div>-->
<!--        <div class="tool4">-->
<!--            <a href="{% url 'clients:merge_video'%}">-->
<!--                <div class="tool4-child"></div>-->
<!--                <div class="merge">Merge</div>-->
<!--                <img class="merged-1-icon" alt="" src="{% static 'clients/images/merged-1@2x.png' %}" />-->
<!--            </a>-->
<!--        </div>-->
<!--        <div class="tool3">-->
<!--            <a href="{% url 'clients:cut_video'%}">-->
<!--                <div class="tool4-child"></div>-->
<!--                <div class="cut">Cut</div>-->
<!--                <img class="cutting-tool-1-icon" alt="" src="{% static 'clients/images/cuttingtool-1@2x.png' %}" />-->
<!--            </a>-->
<!--        </div>-->
<!--        <div class="tool2">-->
<!--            <a href="{% url 'clients:loop_video'%}">-->
<!--                <div class="tool4-child"></div>-->
<!--                <div class="loop">Loop</div>-->
<!--                <img class="loop-1-icon" alt="" src="{% static 'clients/images/loop-1@2x.png' %}" />-->
<!--            </a>-->
<!--        </div>-->
<!--        <div class="tool1">-->
<!--            <a href="{% url 'clients:crop_video'%}">-->
<!--                <div class="tool4-child"></div>-->
<!--                <div class="crop">Crop</div>-->
<!--                <img class="crop-1-icon" alt="" src="{% static 'clients/images/crop-1@2x.png' %}" />-->
<!--            </a>-->
<!--        </div>-->
<!--    </div>-->

<!--    <div class="about">-->
<!--        <div class="your-all-in-one-online"> Your all-in-one online video editor </div>-->
<!--        <div class="make-your-own"> Make your own video from scratch, edit it and add music — all in one screen! Our seamless video editor allows you to manage the added media easily with the help of a multi-track timeline. </div>-->
<!--        <img class="unsplashtqpypka92k8-icon" alt="" src="{% static 'clients/images/unsplashtqpypka92k8@2x.png' %}" />-->
<!--    </div>-->

<!--</div>-->
{% endblock content %}

Web_VideoEditing/clients/templates/clients/subtitle.html
{% extends "clients/base_tool.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'clients/css/add_subtitles.css' %}" />
{% endblock stylesheets %}
{% block content %}
<div class="h-100">
    <div class="row content-upload_subtitle">
        <div class="file-source-btn">
            <form method="post" action="{% url 'clients:subtitle' id=id %}" id="formUpload" enctype="multipart/form-data">
                {% csrf_token %}
                <input id="upload-subtitle" type="file"
                       name="sub_file" class="file-input">
                <label for="upload-subtitle" class="file-btn">
                    <span><i class="fas fa-file-alt mr-1"></i>Upload .SRT</span>
                </label>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script>

    $(document).ready(function (){
        $('#upload-subtitle').on('change', function() {
            let fileInput = document.getElementById('upload-subtitle');
            let file = fileInput.files[0];

            if (file) {
                var fileName = file.name;
                var fileExtension = fileName.split('.').pop();
                if (fileExtension.toLowerCase() === 'srt') {
                    $('#formUpload').submit();
                } else {
                    alert('Please select a .srt file.');
                }
            } else {
                alert('Please select a .srt file.');
            }
        });
    })

    $('.btn-back').on('click', function () {
        window.history.back();
    });

</script>
{% endblock script %}

Web_VideoEditing/clients/templates/clients/subtitle_voice.html
{% extends "clients/base_tool.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'clients/css/add_subtitles.css' %}" />
{% endblock stylesheets %}
{% block content %}
<div class="h-100">
    <div class="row content-upload_subtitle">
        <div class="file-source-btn">
            <form method="post" action="{% url 'clients:subtitle_voice' id=id %}" id="formUpload" enctype="multipart/form-data">
                {% csrf_token %}
                <input id="upload-subtitle" type="file"
                       name="sub_file" class="file-input">
                <label for="upload-subtitle" class="file-btn">
                    <span><i class="fas fa-file-alt mr-1"></i>Upload .SRT</span>
                </label>
            </form>
        </div>
    </div>
</div>
{% endblock content %}
{% block script %}
<script>

    $(document).ready(function (){
        $('#upload-subtitle').on('change', function() {
            let fileInput = document.getElementById('upload-subtitle');
            let file = fileInput.files[0];

            if (file) {
                var fileName = file.name;
                var fileExtension = fileName.split('.').pop();
                if (fileExtension.toLowerCase() === 'srt') {
                    $('#formUpload').submit();
                } else {
                    alert('Please select a .srt file.');
                }
            } else {
                alert('Please select a .srt file.');
            }
        });
    })

    $('.btn-back').on('click', function () {
        window.history.back();
    });

</script>
{% endblock script %}