Web_VideoEditing/Web_VideoEditing/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/",include('users.urls')),
    path("", include('clients.urls')),
    path("administrators/", include('administrators.urls')),
    path("user_project/", include('user_project.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_VideoEditing/clients/urls.py
from django.urls import path, include
from .import views

app_name = 'clients'
urlpatterns = [
    path('', views.home, name="home"),
    path('all_tools/', views.all_tools, name="all_tools"),
    path('add_subtitles/', views.subtitle_video, name="add_subtitles"),
    path('add_subtitles_tool/<int:id>/<int:subtitle_id>/', views.add_subtitles_tool, name="add_subtitles_tool"),
    path('preview_add_subtitles', views.preview_add_subtitles, name="preview_add_subtitles"),
    path('subtitle/<int:id>/', views.subtitle, name="subtitle"),
    path('merge_video/', views.merge_video, name="merge_video"),
    path('preview_merge_video/', views.preview_merge_video, name='preview_merge_video'),
    path('merge_tools/<int:id>/', views.merge_tools, name="merge_tools"),
    path('export_merge_video', views.export_merge_video, name="export_merge_video"),
    path('crop_video/', views.crop_video, name="crop_video"),
    path('crop_tool/<int:id>/', views.crop_tool, name="crop_tool"),
    path('preview_crop_video', views.preview_crop_video, name="preview_crop_video"),
    path('export_crop_video', views.export_crop_video, name="export_crop_video"),
    path('cut_tool/<int:id>/', views.cut_tool, name="cut_tool"),
    path('cut_video/', views.cut_video, name="cut_video"),
    path('loop_video/', views.loop_video, name="loop_video"),
    path('loop_tool/<int:id>/', views.loop_tool, name="loop_tool"),
    path('export_loop_video', views.export_loop_video, name="export_loop_video"),
    path('preview_cut_video', views.preview_cut_video, name="preview_cut_video"),
    path('export_video', views.export_video, name="export_video"),
    path('add_voice_tool/<int:id>/<int:subtitle_id>/', views.add_voice_tool, name="add_voice_tool"),
    path('add_voice/', views.add_voice, name="add_voice"),
    path('subtitle_voice/<int:id>/', views.subtitle_voice, name="subtitle_voice"),
    path('upload_subtitle', views.upload_subtitle, name="upload_subtitle"),
    path('preview_voice_to_video', views.preview_voice_to_video, name="preview_voice_to_video"),


]

Web_VideoEditing/user_project/urls.py
from django.urls import path
from . import views

app_name = 'user_project'
urlpatterns = [
path('<int:id>/', views.home, name='index'),
path('forgot_password/', views.forgot_password, name='forgot_password'),
path('profile/<int:user_id>/', views.profile, name='profile'),
path('delete_video/<int:pk>/', views.delete_video, name='delete_video'),
path('edit_user/', views.edit_user, name='edit_user'),
# path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
path('download_video/<int:pk>/', views.download_video, name='download_video'),
path('edited_video/', views.edited_video, name='edited_video'),



]

Web_VideoEditing/users/urls.py
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # path('', views.home, name="home"),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
]

Web_VideoEditing/user_project/views.py
from django.shortcuts import render, redirect
from users.models import Users
from clients.models import Upload, UserUpload
from django.http import HttpResponse
from django.urls import reverse
from users.views import base_context
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
import os
from django.http import FileResponse
from django.utils.encoding import smart_str


def check_user_role(request):
    if 'username' not in request.session:
        return redirect('users:signin')
    username = request.session.get('username', None)
    user_profile = Users.objects.get(username=username) if username else None
    if user_profile.role == 'admin':
        return redirect('administrators:index')
    return None

def home(request, id):
    user = Users.objects.get(pk=id)
    user_uploads = UserUpload.objects.filter(user=user)
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request, 'user_project/index.html', {'user': user, 'user_uploads': user_uploads, 'user_profile': user_profile})

def forgot_password(request):
    redirect_result = check_user_role(request)
    if redirect_result:
        return redirect_result
    context = base_context(request)
    user_profile = context['user_profile']
    return render(request, 'user_project/forgot_password.html',{'user_profile': user_profile})

# def profile(request,user_id):
#     user_profile1 = Users.objects.get(id=user_id)
#     context = base_context(request)
#     user_profile = context['user_profile']
#     return render(request, 'user_project/profile.html', {'user_profile1':user_profile1,'user_profile':user_profile})

def profile(request, user_id):
    user_profile1 = get_object_or_404(Users, id=user_id)
    context = base_context(request)
    user_profile = context['user_profile']

    if request.method == 'POST':
        # Retrieve the submitted form data
        new_name = request.POST.get('editName')
        new_email = request.POST.get('editEmail')
        new_image = request.FILES.get('image')

        # Update the user profile
        user_profile1.username = new_name
        user_profile1.email = new_email

        # Save the uploaded image if provided
        if new_image:
            user_profile1.image = new_image

        user_profile1.save()

    return render(request, 'user_project/profile.html', {'user_profile1': user_profile1, 'user_profile': user_profile})


def delete_video(request, pk):
    user_upload = get_object_or_404(UserUpload, pk=pk)
    user_upload.delete()
    return redirect('user_project:index', id=user_upload.user.id)

def edit_user(request):
    pass

# def download_video(request, pk):
#     user_upload = get_object_or_404(UserUpload, pk=pk)
#     user_upload.delete()
#     return redirect('user_project:index', id=user_upload.user.id)

def download_video(request, pk):
    upload = get_object_or_404(Upload, pk=pk)

    # Get the path of the video file
    video_path = upload.path_video.path

    # Open the video file
    video_file = open(video_path, 'rb')

    # Create a FileResponse with the video file
    response = FileResponse(video_file)

    # Set the content type and headers for the response
    response['Content-Type'] = 'video/mp4'
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(upload.path_video.name)

    return response



def edited_video(request):
    return render(request, 'user_project/edited_video.html')

Web_VideoEditing/user_project/templates/user_project/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>{{WEBSITE_FOOTER_NAME}} - {% block title %} {% endblock %}</title>

        <!-- Custom fonts for this template-->
        <link href="{% static 'user_project/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{% static 'user_project/css/sb-admin-2.min.css' %}" rel="stylesheet">

        {% block css %}
        {% endblock %}

        {% block js_head %}
        {% endblock %}
    </head>
    <body id="page-top">
        <div id="wrapper">
            {% include 'user_project/components/sidebar.html' %}
            <div id="content-wrapper" class="d-flex flex-column">
                <div id="content">
                    {% include 'user_project/components/navbar.html' %}
                    {% block container_fluid %}
                    {% endblock %}
                </div>
                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
        </a>
        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                        <a class="btn btn-primary" href="{% url 'users:signout'%}" >Logout</a>
                    </div>
                </div>
            </div>
        </div>
        <script src="{% static 'user_project/vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'user_project/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'user_project/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
        <script src="{% static 'user_project/js/sb-admin-2.min.js' %}"></script>
        {% comment %} <script src="{% static 'user_project/vendor/chart.js/Chart.min.js' %}"></script>
        <script src="{% static 'user_project/js/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'user_project/js/demo/chart-pie-demo.js' %}"></script>
        <script src="{% static 'user_project/js/demo/chart-bar-demo.js' %}"></script> {% endcomment %}

        {% block js_body %}
        {% endblock %}
    </body>
</html>

Web_VideoEditing/user_project/templates/user_project/base_x.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{{WEBSITE_FOOTER_NAME}} - {% block title %} {% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'user_project/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'user_project/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!--Added-->
  <link rel="stylesheet" type="text/css" href="{% static 'user_project/resource/css/base_x.css' %}">

  {% block css %}
  {% endblock %}

  {% block js_head %}
  {% endblock %}
</head>

<body> <!-- class="bg-gradient-primary" -->
  {% include 'user_project/components/navbar_x.html' %}


  {% block container %}
  {% endblock %}

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'user_project/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'user_project/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'user_project/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'user_project/js/sb-admin-2.min.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function() {
        $('.data-top-right-link').click(function() {
            let next_location = $(this).find('a').attr('href')
            location.href = next_location
        })
    })
  </script>
  {% block js_body %}
  {% endblock %}
</body>

</html>

Web_VideoEditing/user_project/templates/user_project/forgot_password.html
{% extends 'user_project/base_x.html' %}
{% load static %}


{% block title %} Forgot password {% endblock %}


{% block container %}
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <div class="row">
                        <div class="col-lg-8 offset-lg-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <label for="email">Email Address</label>
                                        <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <a class="btn btn-primary btn-user btn-block">
                                    Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" >Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small">Already have an account? Login!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Web_VideoEditing/user_project/templates/user_project/index.html
{% extends 'user_project/base.html' %}
{% load static %}

{% block title %} My Project {% endblock %}

{% block container_fluid %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">My projects</h1>
        <a href="{% url 'clients:all_tools' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa-solid fa-plus"></i> New project</a>
    </div>
    <div class="row">
        {% for user_upload in user_uploads %}
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 src="{{ user_upload.upload.title_video }}" class="m-0 font-weight-bold text-primary">{{user_upload.upload.title_video }}</h6>
                    <div class="dropdown no-arrow">
                        <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                            <div class="dropdown-header">Action:</div>
                            <a href="{% url 'user_project:delete_video' pk=user_upload.id %}" class="dropdown-item" id="delete-video-btn">Delete Video</a>
                            <a href="{% url 'user_project:download_video' pk=user_upload.id %}" class="dropdown-item" id="delete-video-btn">Download Video</a>
                        </div>
                    </div>
                </div>
                <div class="video-container">
                    <video class="responsive-video" controls>
                        <source src="{{ user_upload.upload.path_video.url }}" type="video/mp4">
                        Your browser does not support the video tag.
                    </video>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Web_VideoEditing/user_project/templates/user_project/profile.html
{% extends 'user_project/base.html' %}
{% load static %}

{% block title %} Profile {% endblock %}

{% block container_fluid %}

<link href="{% static 'user_project/css/sb-admin-2.min.css' %}" rel="stylesheet">
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Profile</h1>
    </div>
      <div class="profile-container" id="userProfile">
        <img src="{{ user_profile1.image.url }}" alt="{{ user_profile1.username }}'s image" id="user-image">
        <h2 id="userName">{{ user_profile1.username }}</h2>
        <p id="userEmail">{{ user_profile1.email }}</p>

        <button class="edit-btn" onclick="openEditModal()">Edit</button>
        {% comment %} <button class="delete-btn" onclick="openDeleteModal()">Delete</button> {% endcomment %}
      </div>

      <div id="edit-modal">
        <form method="POST" action="{% url 'user_project:profile' user_profile1.id %}" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-content">
            <span class="close" onclick="closeEditModal()">&times;</span>
            <h2 class="form-name">Edit User Profile</h2>
            <label class="input-image" for="editImage">Image:</label>
            <input class="edit-image" type="file" id="editImage" accept="image/*" name="image">
            <label for="editName">Name:</label>
            <input class="input-name" type="text" id="editName" name="editName" value="{{ user_profile1.username }}">
            <label for="editEmail">Email:</label>
            <input class="input-mail" type="email" id="editEmail" name="editEmail" value="{{ user_profile1.email }}">
            <button class="input-save" type="submit">Save Changes</button>
          </div>
        </form>
      </div>

      {% comment %} <div id="delete-modal">
        <div class="modal-content">
          <span class="close" onclick="closeDeleteModal()">&times;</span>
          <h2>Delete User Profile</h2>
          <p>Are you sure you want to delete this user profile?</p>
          <a href="#" onclick="deleteProfile({{ user.id }})">Delete</a>
        </div>
      </div> {% endcomment %}

      <script>
        function openEditModal() {
          document.getElementById('edit-modal').style.display = 'block';
        }
    
        function closeEditModal() {
          document.getElementById('edit-modal').style.display = 'none';
        }
    
        function openDeleteModal() {
          document.getElementById('delete-modal').style.display = 'block';
        }
    
        function closeDeleteModal() {
          document.getElementById('delete-modal').style.display = 'none';
        }
    
        function deleteProfile() {
          const userProfile = document.getElementById('userProfile');
          userProfile.parentNode.removeChild(userProfile);
          closeDeleteModal();
        }

            function deleteProfile(user_id) {
        if (confirm("Are you sure you want to delete this user profile?")) {
            fetch(`/delete_user/${user_id}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/json',
                },
            })
            .then(response => {
                if (response.ok) {
                    // Xóa thành công, thực hiện các xử lý khác nếu cần
                    location.reload();  // Tải lại trang sau khi xóa
                } else {
                    // Xử lý lỗi khi không xóa thành công
                    console.error('Delete user failed.');
                }
            })
            .catch(error => {
                // Xử lý lỗi khi yêu cầu không thành công
                console.error('Delete user request failed.', error);
            });
        }
    }
      </script>

</div>
{% endblock %}

Web_VideoEditing/user_project/templates/user_project/user_videos.html
{% extends 'user_project/base.html' %}
{% load static %}

{% block title %} My Project {% endblock %}

{% block container_fluid %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">My projects</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fa-solid fa-plus"></i> New project</a>
    </div>

    {% for user_upload in user_uploads %}

        <div class="row">
            <div class="col-xl-4 col-lg-5">
                <div class="card shadow mb-4">
                    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                        <h6 class="m-0 font-weight-bold text-primary">New project</h6>
                        <div class="dropdown no-arrow">
                            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                                <div class="dropdown-header">Dropdown Header:</div>
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="chart-pie pt-4 pb-2">
                            {% comment %} <canvas id="myPieChart"></canvas> {% endcomment %}
                            <video width="320" height="240" controls>
                                <source src="{{ user_upload.upload.path_video.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                            <p>{{ user_upload.upload.title_video }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}


</div>
{% endblock %}